### ISSUE TITLE
Support setting argument/return types in the docstring

### ISSUE THREAD

**Issue by thebigmunch** [pawamoy/pytkdocs#10]
Not everybody uses (or wants to use) type hints in their code. Not supporting setting types in the docstrings limits the user base of mkdocstrings to those that do.

Would you be amenable to adding support for setting the types in the docstring? It would probably make most sense to follow the [Google style](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google) as done with sections.

Thanks for the consideration and the promising package.

**Comment by thebigmunch** [comment]
> I'll transfer this issue over to pytkdocs since it's now the project that is responsible for loading Python documentation, including docstrings

Well, this issue was about mkdocstrings supporting this; doesn't really belong in the tracker for the module created with the lower-level functionality to add that support to mkdocstrings. In my eyes, it should stay on the mkdocstrings tracker and be closed when mkdocstrings has the ability to do this. Just because py-tkdocs adds support for it doesn't mean mkdocstrings gets that support, at least not right away. But it's your call.

**Comment by pawamoy** [comment]
pytkdocs and mkdocstrings roadmaps stay tightly coupled. With the upcoming release of mkdocstrings it'll be easy to update it with new pytkdocs features.

If it's a question of issue visibility, feel free to open an issue on mkdocstrings linking back to this one, but I think discussion about this feature request should happen on this repo.

Organizing issues also helps me deal with them!

**Comment by thebigmunch** [comment]
Well, this issue topic is implicitly expected from a docstring parser, so it doesn't really make sense to be here. And, if the solution is to open the same issue back up on mkdocstrings, that seems to say that is where this issue should have stayed. Then if you  think it needed to be here as well, you could open an issue here linked back to it. All the discussion in this issue pertains to mkdocstrings, not py-tkdocs.

**Comment by pawamoy** [comment]
> Well, this issue topic is implicitly expected from a docstring parser.

No it's not, because I never signed anything saying I must support all styles in docstrings. Even more, this projet is *not* a docstring parser. It's a documentation-tree/object-tree retriever/loader. It happens to also parse docstrings because it was the most straight forward way to bring  better support for them in mkdocstrings. In the contributing issue of mkdocstrings, I listed a "proper Google-style docstring markdown extension" as something that could really beneficiate mkdocstrings. *This markdown extension* would be the docstring parser.

> so it doesn't really make sense to be here

So the issue about parsing docstring makes no sense in the project which parses them? You're asking for a particular style to be supported (not speaking about it's popularity or use), so I think it makes total sense.

> if the solution is to open the same issue back up on mkdocstrings, that seems to say that is where this issue should have stayed.

A solution to what? This debate?

> Then if you think it needed to be here as well, you could open an issue here linked back to it.

Yes I could have done that, but I didn't. Should we move forward or continue arguing? In your previous comment, you said "it's your call", so I'm invoking that.

Now, just so you know, if we implement this feature here, it should immediately be available in mkdocstrings, transparently, because of how we build data here and render it there. So you don't have to worry about that.

---

I feel like I'm going down a dangerous road with you, replying in this manner (bullet point), and that this conversation could never end. I'm trying my best to do the free, volunteer work of developing Python projects, because I love it, and I can feel insulted as well sometimes. I hope we can agree to put aside the details of issue management and work toward the goal of implementing the feature.

**Comment by pawamoy** [comment]
@thebigmunch could you try the latest release of `mkdocstrings` (v0.10.0)? I added support for type hints in docstrings. I'd like to know if this is working for you. I'll close this issue, open new ones if you encounter any issues.
