### ISSUE TITLE
CollectionError swallows exception

### ISSUE THREAD

**Issue by stufisher** [pawamoy/pytkdocs#53]
**Is your feature request related to a problem? Please describe.**
I've noticed when collecting, pytkdocs swallows errors from the module in question. For example if there is an issue importing a module, It returns that:
```
AttributeError: module 'module.x.y' has no attribute 'z'
```
However this usually points to something amiss in the module (unmet dependency). If i open up a cli and try to import the module by hand i can see whats going on.

**Describe the solution you'd like**
It would be nice if pytkdocs could bubble the underlying exception through to CollectionError for easier diagnosis.

**Comment by pawamoy** [comment]
I don't think the traceback would be useful, because it happens [here](https://github.com/pawamoy/pytkdocs/blob/master/src/pytkdocs/loader.py#L165). You would only see the stack down to pytkdocs.

This is related to https://github.com/pawamoy/mkdocstrings/issues/127. I'll mark this as error handling :slightly_smiling_face:

**Comment by pawamoy** [comment]
You can now use the [`new_path_syntax`](https://pawamoy.github.io/pytkdocs/#details-on-new_path_syntax) option to prevent pytkdocs from swallowing the exception.

In mkdocs.yml:

```yaml
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            new_path_syntax: yes
```
